version: '2'
linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - gocritic
    - godot
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - testifylint
    - wastedassign
  settings:
    gosec:
      includes:
        - G102
        - G106
        - G108
        - G109
        - G111
        - G112
        - G201
        - G203
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - structcheck
          - unused
        text: '`data` is unused'
      - linters:
          - revive
        text: 'var-naming:'
      - linters:
          - revive
        text: 'exported:'
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/legendaryum-metaverse/auth
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
