#  https://github.com/gin-gonic/gin/blob/master/.golangci.yml
#  https://github.com/prometheus/prometheus/blob/main/.golangci.yml
#  golangci-lint run -c .golangci.yml
run:
  timeout: 5m
output:
  sort-results: true
linters:
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - gofumpt
    - copyloopvar
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - revive
    - wastedassign
    #    - depguard
    - gocritic
    - godot
    - predeclared
    - unused
    - testifylint

linters-settings:
  testifylint:
    # Enable all checkers (https://github.com/Antonboom/testifylint#checkers).
    # Default: false
    enable-all: true
  goimports:
    local-prefixes: github.com/legendaryum-metaverse/auth
  gofumpt:
    extra-rules: true
  gosec:
    # To select a subset of rules to run.
    # Available rules: https://github.com/securego/gosec#available-rules
    # Default: [] - means include all rules
    includes:
      - G102
      - G106
      - G108
      - G109
      - G111
      - G112
      - G201
      - G203

issues:
  exclude-rules:
    - linters:
        - structcheck
        - unused
      text: '`data` is unused'
    #    - linters:
    #        - staticcheck
    #      text: "SA1019:"
    - linters:
        - revive
      text: 'var-naming:'
    - linters:
        - revive
      text: 'exported:'
    - path: _test\.go
      linters:
        - gosec # security is not make sense in tests
    - linters:
        - revive
      path: _test\.go
