services:
  # TEST needs rabbit running in localhost:5672
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 1234
    restart: on-failure
    healthcheck:
      test: rabbitmq-diagnostics -q alarms || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
  wait-for-services-to-be-ready:
    image: hello-world
    depends_on:
      rabbitmq:
        condition: service_healthy
