name: check_minor_dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 1,15 * *' # 5:30 PM UTC on the 1st and 15th of every month
env:
  FORCE_COLOR: 3

defaults:
  run:
    shell: bash

# *************************   TRIGGERING FURTHER WORKFLOW RUNS ***************************
# https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

jobs:
  update_minor_dependencies:
    timeout-minutes: 2
    if: github.event.repository.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main
      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/go.mod
      - name: Update dependencies
        run: |
          go get -u ./...
          go mod tidy
          go mod verify

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'dependencies: Upgrade GO packages (automated)'
          branch: 'upgrade-go-packages'
          commit-message: 'dependencies: Upgrade GO packages (automated)'
          body: |
            ### ⚠ Importante leer antes de hacer merge a main
            >Cerrar esta **PR** y abrirla de nuevo para que corran las **actions**
            de **code-quality-check**.

            >Luego _merge_ a **main**.
